#! python3
#bigFileSearcher-Searches for files greater than 100 MB and returns their
#absolute path

import os
folder = 'C:\\Users\hairy\Downloads'
for folders, subfolders, filenames in os.walk('C:\\Users\hairy\Downloads'):
    for filename in filenames:
        if os.path.getsize(os.path.join(folders, filename)) >= 1000000000:
            print(os.path.join(folders, filename) +  ' is over 1000 MB')
print('done')
